version: '3.7'

services:
  build_and_publish:
    build:
      context: publish
      args:
        GEM_VGS_PUBLISH_TOKEN: ${GEM_VGS_PUBLISH_TOKEN}
        LIB_VERSION: ${LIB_VERSION}
    volumes:
      - ./:/src/
  test:
    build:
      context: .
      dockerfile: test/Dockerfile